namespace GamesPlatform.Core.Model.User;

public class UserProfile
{
    public string Id { get; set; } 
    public string ProfileName { get; set; } 
    public string FavouriteGame { get; set; }
    // TODO: Profile picture
    
    public UserProfile(string profileName, string favouriteGame)
    {
        // Id would be autogenerated if it had guid type
        Id = Guid.NewGuid().ToString();
        ProfileName = profileName;
        FavouriteGame = favouriteGame;
    }
}
