using GamesPlatform.Core.Model.Reviews;

namespace GamesPlatform.Core.Model.User;

public class UserProfile
{
    public string Id { get; set; } 
    public string ProfileName { get; set; } 
    public string FavouriteGame { get; set; }
    public List<Review>? UserReviews { get; set; }
    // TODO: Profile picture
    
    public UserProfile(string profileName, string favouriteGame)
    {
        // Id would be autogenerated if it had guid type
        Id = Guid.NewGuid().ToString();
        ProfileName = profileName;
        FavouriteGame = favouriteGame;
    }
}
